version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ebook_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: ebook_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: ebook_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgrespassword@postgres:5432/ebook_db?schema=public'
      JWT_SECRET: 'super_secret_jwt_key_2026'
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebook_frontend
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  postgres_data:
